spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./data/demodb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init.mode: always
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
